In [1]:
import torch
import numpy as np

#data_check
a = torch.randn(2, 3)
a.type()

'torch.FloatTensor'

In [2]:
type(a)

torch.Tensor

In [3]:
isinstance(a, torch.FloatTensor)

True

In [4]:
isinstance(a, torch.cuda.FloatTensor)


False

In [5]:
b = torch.tensor(6)
b

tensor(6)

In [6]:
b.shape

torch.Size([])

In [7]:
b.size()

torch.Size([])

In [8]:
b.dim()

0

In [9]:
b.type()

'torch.LongTensor'

In [10]:
c = torch.tensor(9.)
c

tensor(9.)

In [11]:
c.type()

'torch.FloatTensor'

In [20]:
torch.tensor([1.1])#bias

tensor([1.1000])

In [13]:
torch.tensor([1.1,2.2])

tensor([1.1000, 2.2000])

In [14]:
torch.tensor([1.1,2.2]).shape

torch.Size([2])

In [15]:
torch.FloatTensor(1)

tensor([-9388.5156])

In [16]:
torch.FloatTensor(2)

tensor([-9.3885e+03,  4.5909e-41])

In [17]:
data  =  np.ones(2)

In [18]:
data

array([1., 1.])

In [19]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [22]:
torch.ones(2,2).shape

torch.Size([2, 2])

In [27]:
torch.ones(2,2,2).size()

torch.Size([2, 2, 2])

In [26]:
torch.ones(2,2,2).dim()

3